language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.10.6
addons:
  apt:
    packages:
      - libav-tools
script:
  - 'bundle exec rake spec'
  - 'bundle exec rake features'
  - 'bundle exec rake coveralls:push'
  - 'bundle exec rake rubocop'
