---
os: rpi
lang: en
player:
  omxplayer:
    default_volume: -2100
    path: omxplayer
    volume_step_secs: 3
  player: omxplayer
  vlc:
    default_volume: 128
    fullscreen: true
    path: vlc
    rc_host: localhost
    rc_port: 50000
    volume_fadein_secs: 0.125
    volume_step: 1.0
    wait_secs_after_run: 5
    wait_secs_if_http: 3
rng:
  hwrng:
    source: /dev/random
  method: hwrng
  random.org:
    apikey: ""
sources:
  download:
    device: /dev/sda
    dir: /mnt/.budik/downloads/
    method: remove
    mount: "udisksctl mount -b $partition"
    partition: /dev/sda1
    sleep: ""
    unmount: "udisksctl unmount -b $partition"
  path: ~/.budik/sources.yml
tv:
  available: true
  use_if_no_video: true
  wait_secs_after_on: 15
